# Generated by Django 5.0.1 on 2025-09-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='notes',
        ),
        migrations.AlterField(
            model_name='member',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.assembly'),
        ),
    ]
