# Generated by Django 5.0.1 on 2025-09-30 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_member_notes_alter_member_assembly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('Cell', 'Cell'), ('MODERATOR', 'Moderator')], default='Cell', max_length=100)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.assembly')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_admins', to='core.cell')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='core.member')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
