# Generated by Django 5.0.1 on 2025-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='month_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
