# Generated by Django 5.0.1 on 2025-10-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_month_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='family',
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='core.assembly')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to='core.member')),
                ('members', models.ManyToManyField(blank=True, related_name='committees', to='core.member')),
            ],
            options={
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
