# Generated by Django 5.0.1 on 2025-10-02 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_member_family_committee_delete_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='members',
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='core.member')),
            ],
            options={
                'verbose_name_plural': 'Committee Memberships',
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
