# Generated by Django 5.0.1 on 2025-10-09 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_committee_assembly_remove_committee_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_unit_members', to='core.unit'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('acquired_from', models.CharField(blank=True, max_length=200)),
                ('Brand', models.CharField(blank=True, max_length=100)),
                ('Model', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'Currently in Use'), ('reserved', 'Reserved for Event'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('lost', 'Lost')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent - Like new'), ('good', 'Good - Minor wear'), ('fair', 'Fair - Needs attention'), ('poor', 'Poor - Needs replacement'), ('broken', 'Broken - Unusable')], default='good', max_length=20)),
                ('location', models.CharField(blank=True, help_text="Specific location (e.g., 'Main Sanctuary', 'Kitchen Cabinet', 'Youth Room')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Special instructions, usage notes, or maintenance requirements')),
                ('image', models.ImageField(blank=True, help_text='Photo of the item', null=True, upload_to='inventory_images/')),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_inventries', to='core.admin')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.assembly')),
            ],
            options={
                'verbose_name_plural': 'Inventries',
                'ordering': ['name'],
            },
        ),
    ]
