# Generated by Django 5.0.1 on 2025-10-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_other_unit_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='level',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('Cell', 'Cell'), ('MODERATOR', 'Moderator'), ('Inventory', 'Inventory')], default='Cell', max_length=100),
        ),
    ]
