# Generated by Django 5.0.1 on 2025-10-10 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='comment',
            field=models.TextField(blank=True, help_text='Here you can add the notes on specifics that are not metioned. e.g. 5 are bad, 2 useable, 3 needs repair....', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Brand',
            field=models.CharField(help_text='Use Manufacturer name if item has no brand or add Brand name', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='acquired_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='acquired_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(help_text="Specific location (e.g., 'Main Sanctuary', 'Kitchen Cabinet', 'Youth Room')", max_length=200),
        ),
    ]
